import type { AxisAgent, AxisBuildOrderItem, AxisBuildScreen, AxisObjectContract } from "./types";

export const axisBuildAgents: AxisAgent[] = [
  {
    id: 1,
    name: "Axis Router Agent",
    purpose: "Understands the request and routes it to the right agent.",
    status: "Wired as static routing contract.",
    futureWiring: "/api/axis/run router.",
    accent: "purple",
    routeContract: {
      accepts: "One user command plus optional mode or source.",
      decides: "The first Axis capability that should receive the request.",
      returns: "A routing decision for the next agent. No backend call yet.",
    },
  },
  {
    id: 2,
    name: "Axis LLM Orchestrator Agent",
    purpose: "Chooses the best LLM, prompt strategy, context, and verification for each task.",
    status: "Wired as static orchestration contract.",
    futureWiring: "model orchestration layer.",
    accent: "gold",
    orchestrationContract: {
      accepts: [
        "routed task from Axis Router Agent",
        "user intent",
        "selected mode",
        "available context",
        "attached media references",
        "session/player/project context",
      ],
      decides: [
        "best model path",
        "prompt strategy",
        "needed context",
        "verification/checking layer",
        "fallback path if one model/tool is not enough",
        "whether to hand off to another Axis agent",
      ],
      returns: [
        "executionPlan",
        "selectedCapabilityPath",
        "requiredContext",
        "verificationPlan",
        "nextAgentId",
      ],
    },
  },
  {
    id: 3,
    name: "Media Intake Agent",
    purpose: "Handles uploads, captures, and turns media into Axis objects.",
    status: "Wired as static media intake contract.",
    futureWiring: "upload, Cloudflare/Mux, Supabase storage.",
    accent: "blue",
    mediaIntakeContract: {
      accepts: [
        "executionPlan from Axis LLM Orchestrator Agent",
        "uploaded file reference",
        "camera capture reference",
        "audio/video/image source metadata",
        "current session/player/project context",
      ],
      decides: [
        "whether the source is video, image, audio, document, or note",
        "which intake path should prepare the source",
        "what metadata must be attached before processing",
        "whether the source is ready for another Axis agent",
        "what safety or size limits need review before upload wiring",
      ],
      returns: [
        "axisSourceObject",
        "sourceType",
        "sourceMetadata",
        "storagePlan",
        "nextAgentId",
      ],
    },
  },
  {
    id: 4,
    name: "Voice Agent",
    purpose: "Listens in real time and turns speech into structured Axis data.",
    status: "Wired as static voice contract.",
    futureWiring: "mic, transcription, voice notes.",
    accent: "green",
    voiceContract: {
      accepts: [
        "executionPlan from Axis LLM Orchestrator Agent",
        "audio source object from Media Intake Agent",
        "live microphone intent",
        "speaker/session context",
        "current command or question",
      ],
      decides: [
        "whether speech is live input, a saved voice note, or media audio",
        "whether the voice source needs transcription, cleanup, or summary",
        "what structured note shape should be produced",
        "whether the result should return to Axis Router or another agent",
        "what confidence or review flag is needed before using the transcript",
      ],
      returns: [
        "voiceSourceObject",
        "transcriptPlan",
        "structuredVoiceNote",
        "reviewFlags",
        "nextAgentId",
      ],
    },
  },
  {
    id: 5,
    name: "Vision Agent",
    purpose: "Detects players, ball, objects, court areas, body positions, and more.",
    status: "Wired as static vision contract.",
    futureWiring: "vision/cv pipeline.",
    accent: "orange",
    visionContract: {
      accepts: [
        "executionPlan from Axis LLM Orchestrator Agent",
        "image or video source object from Media Intake Agent",
        "frame or clip reference",
        "current session/player/project context",
        "requested visual question or detection target",
      ],
      decides: [
        "whether the source needs image inspection or video frame analysis",
        "which visual observations should be suggested first",
        "whether player, ball, object, court, or body-position detection is relevant",
        "what confidence or review flag belongs on each suggested observation",
        "whether to hand off to Video Understanding Agent or return suggested observations",
      ],
      returns: [
        "suggestedVisualObservations",
        "detectionTargets",
        "frameReferences",
        "reviewFlags",
        "nextAgentId",
      ],
    },
  },
  {
    id: 6,
    name: "Video Understanding Agent",
    purpose: "Lets the user chat with video, find moments, patterns, and answers.",
    status: "Wired as static video understanding contract.",
    futureWiring: "video analysis, clips, summaries.",
    accent: "cyan",
    videoUnderstandingContract: {
      accepts: [
        "executionPlan from Axis LLM Orchestrator Agent",
        "video source object from Media Intake Agent",
        "suggestedVisualObservations from Vision Agent",
        "clip or timestamp reference",
        "user question about the video",
      ],
      decides: [
        "whether the user needs a moment, pattern, answer, clip, or summary",
        "which frames or time ranges should be inspected first",
        "what visual/audio/context signals should be combined",
        "whether the output should become a clip, note, report input, or next question",
        "whether to hand off to Session Memory Agent or Report Agent",
      ],
      returns: [
        "videoUnderstandingPlan",
        "momentCandidates",
        "patternCandidates",
        "answerDraft",
        "clipPlan",
        "nextAgentId",
      ],
    },
  },
  {
    id: 7,
    name: "Session Memory Agent",
    purpose: "Stores challenge, constraint, reality, result, and next challenge.",
    status: "Wired as static session memory contract.",
    futureWiring: "Supabase memory/session tables.",
    accent: "purple",
    sessionMemoryContract: {
      accepts: [
        "executionPlan from Axis LLM Orchestrator Agent",
        "source objects from Media Intake Agent",
        "voice, vision, or video understanding outputs",
        "current player/session/project context",
        "challenge, constraint, reality, result, and next challenge candidates",
      ],
      decides: [
        "which session facts are worth keeping",
        "which items are only temporary working context",
        "how challenge, constraint, reality, result, and next challenge should be separated",
        "whether the memory candidate needs user confirmation",
        "whether the next handoff is Report Agent or Follow-Up / Sales Agent",
      ],
      returns: [
        "sessionMemoryPlan",
        "memoryCandidates",
        "temporaryContext",
        "confirmationNeeded",
        "nextAgentId",
      ],
    },
  },
  {
    id: 8,
    name: "Report Agent",
    purpose: "Turns evidence into player, parent, coach, and team reports.",
    status: "Wired as static report contract.",
    futureWiring: "report generation, PDF/export, send/share.",
    accent: "gold",
    reportContract: {
      accepts: [
        "executionPlan from Axis LLM Orchestrator Agent",
        "sessionMemoryPlan from Session Memory Agent",
        "approved session facts and summaries",
        "clip, moment, or report input candidates",
        "intended audience: player, parent, coach, or team",
      ],
      decides: [
        "which report shape fits the audience",
        "which claims need support before appearing in the report",
        "which clips or moments should be referenced",
        "whether the report should stay draft-only",
        "whether to hand off to Follow-Up / Sales Agent after report approval",
      ],
      returns: [
        "reportDraftPlan",
        "audienceType",
        "supportedClaimList",
        "clipReferencePlan",
        "exportPlan",
        "nextAgentId",
      ],
    },
  },
  {
    id: 9,
    name: "Follow-Up / Sales Agent",
    purpose: "Turns proof into action: updates, bookings, next steps, parent follow-up.",
    status: "Wired as static follow-up contract.",
    futureWiring: "messages, automations, reminders, booking flows.",
    accent: "green",
    followUpContract: {
      accepts: [
        "executionPlan from Axis LLM Orchestrator Agent",
        "approved report plan from Report Agent",
        "sessionMemoryPlan from Session Memory Agent",
        "audience and consent context",
        "next challenge, booking, update, or reminder candidate",
      ],
      decides: [
        "which follow-up action is appropriate",
        "whether the action is a message, booking, reminder, update, or next challenge",
        "what approval is required before sending anything",
        "which audience should receive the follow-up",
        "whether the action should stay as a draft only",
      ],
      returns: [
        "followUpPlan",
        "audienceType",
        "draftMessage",
        "automationCandidate",
        "approvalRequired",
        "nextActionStatus",
      ],
    },
  },
];

export const axisBuildScreens: AxisBuildScreen[] = [
  {
    id: "home",
    title: "Home Screen",
    items: ["AXIS 9 identity", "New Session button", "Ask Axis button", "9 agent grid", "bottom navigation"],
  },
  {
    id: "sessions",
    title: "Sessions Screen",
    items: ["session list", "today / week / month filters", "processing and complete states"],
  },
  {
    id: "session-detail",
    title: "Session Detail Screen",
    items: ["video thumbnail", "summary", "clips", "notes", "stats", "challenge", "constraint", "result", "next challenge"],
  },
  {
    id: "ask-axis",
    title: "Ask Axis Screen",
    items: ["chat with video/session", "clip reference", "answer card", "next challenge", "mic input"],
  },
  {
    id: "player-profile",
    title: "Player Profile Screen",
    items: ["player image", "sessions", "challenges", "targets hit", "personal bests", "strengths", "opportunities"],
  },
  {
    id: "report",
    title: "Report Screen",
    items: ["player report", "grade", "summary", "strengths", "focus areas", "next challenge", "clips", "send to parent", "download PDF"],
  },
  {
    id: "how-axis-works",
    title: "How Axis Works Section",
    items: ["Capture", "Axis Agents", "Memory", "Proof", "Action"],
  },
];

export const axisSessionContract: AxisObjectContract = {
  name: "AxisSession",
  status: "Wired as local frontend object type.",
  owns: [
    "id",
    "title",
    "optional playerName",
    "sessionType",
    "status",
    "createdAt",
  ],
  doesNotOwn: [
    "media uploads",
    "analysis results",
    "agent execution",
    "proof or evidence",
    "memory persistence",
    "reports",
  ],
  futureWiring: [
    "session persistence",
    "media intake handoff",
    "session detail screen",
    "AxisOutput grouping",
  ],
};

export const axisPlayerContract: AxisObjectContract = {
  name: "AxisPlayer",
  status: "Wired as local frontend object type.",
  owns: [
    "id",
    "displayName",
    "optional jerseyNumber",
    "optional position",
    "status",
    "createdAt",
  ],
  doesNotOwn: [
    "long-term player memory",
    "verified performance truth",
    "stats",
    "media evidence",
    "reports",
    "cross-session history",
  ],
  futureWiring: [
    "player profile screen",
    "session association",
    "report audience context",
    "memory layer only after explicit unlock",
  ],
};

export const axisOutputContract: AxisObjectContract = {
  name: "AxisOutput",
  status: "Wired as universal output object type.",
  owns: [
    "id",
    "title",
    "output type",
    "status",
    "createdAt",
    "optional thumbnailUrl",
    "optional fileUrl",
    "optional summary",
    "optional sourceLabel",
  ],
  doesNotOwn: [
    "backend provider identity",
    "raw API credentials",
    "source truth",
    "verification verdicts",
    "memory records",
    "session persistence",
  ],
  futureWiring: [
    "/api/axis/run result envelope",
    "recent outputs surface",
    "output detail views",
    "artifact/export grouping",
  ],
};

export const axisMediaSourceContract: AxisObjectContract = {
  name: "AxisMediaSource",
  status: "Wired as local media intake draft.",
  owns: [
    "id",
    "fileName",
    "fileType",
    "mediaType",
    "sizeBytes",
    "status",
    "createdAt",
    "optional sessionId",
  ],
  doesNotOwn: [
    "uploaded file bytes",
    "storage URL",
    "Cloudflare/Mux asset",
    "analysis results",
    "evidence verdicts",
    "persistent source record",
  ],
  futureWiring: [
    "real upload transport",
    "storage asset creation",
    "Media Intake Agent handoff",
    "AxisOutput generation",
  ],
};

export const axisObjectContracts: AxisObjectContract[] = [
  axisSessionContract,
  axisPlayerContract,
  axisOutputContract,
  axisMediaSourceContract,
];

export const axisBuildOrder: AxisBuildOrderItem[] = [
  { id: 1, title: "Blank /axis shell" },
  { id: 2, title: "/axis/build-map page" },
  { id: 3, title: "Static Axis 9 agent cards" },
  { id: 4, title: "Static mobile screen references" },
  { id: 5, title: "New Session button" },
  { id: 6, title: "Ask Axis input" },
  {
    id: 7,
    title: "Session object type",
    items: ["AxisSession type exists", "local draft status only", "no persistence yet"],
  },
  {
    id: 8,
    title: "Player object type",
    items: ["AxisPlayer type exists", "profile identity only", "no player memory yet"],
  },
  {
    id: 9,
    title: "AxisOutput object type",
    items: ["AxisOutput type exists", "all result categories share one shape", "no run API wiring yet"],
  },
  {
    id: 10,
    title: "Media intake upload",
    items: ["local file picker exists", "metadata draft only", "no backend upload yet"],
  },
  {
    id: 11,
    title: "Session detail page",
    items: ["local detail surface opens", "shows session facts and drafts", "no route or persistence yet"],
  },
  {
    id: 12,
    title: "Ask Axis chat page",
    items: ["local chat surface exists", "messages stay in frontend state", "no agent response yet"],
  },
  {
    id: 13,
    title: "Player profile page",
    items: ["local profile preview opens", "uses current session player only", "no player memory yet"],
  },
  {
    id: 14,
    title: "Report page",
    items: ["local report draft opens", "shows current session inputs", "no generation, export, or send yet"],
  },
  {
    id: 15,
    title: "Memory persistence",
    items: ["browser localStorage restore exists", "draft session state only", "no Supabase or player memory yet"],
  },
  {
    id: 16,
    title: "Report export/send",
    items: ["local export/send draft actions exist", "no PDF generated", "nothing is sent yet"],
  },
  {
    id: 17,
    title: "Follow-up automation",
    items: ["local follow-up draft action exists", "no message sent", "no automation scheduled yet"],
  },
];
