import type { AxisAgent, AxisBuildOrderItem, AxisBuildScreen, AxisObjectContract } from "./types";

export const axisBuildAgents: AxisAgent[] = [
  {
    id: 1,
    name: "Axis Router Agent",
    purpose: "Understands the request and routes it to the right agent.",
    status: "Wired as static routing contract.",
    futureWiring: "/api/axis/run router.",
    accent: "purple",
    routeContract: {
      accepts: "One user command plus optional mode or source.",
      decides: "The first Axis capability that should receive the request.",
      returns: "A routing decision for the next agent. No backend call yet.",
    },
  },
  {
    id: 2,
    name: "Axis LLM Orchestrator Agent",
    purpose: "Chooses the best LLM, prompt strategy, context, and verification for each task.",
    status: "Wired as static orchestration contract.",
    futureWiring: "model orchestration layer.",
    accent: "gold",
    orchestrationContract: {
      accepts: [
        "routed task from Axis Router Agent",
        "user intent",
        "selected mode",
        "available context",
        "attached media references",
        "session/player/project context",
      ],
      decides: [
        "best model path",
        "prompt strategy",
        "needed context",
        "verification/checking layer",
        "fallback path if one model/tool is not enough",
        "whether to hand off to another Axis agent",
      ],
      returns: [
        "executionPlan",
        "selectedCapabilityPath",
        "requiredContext",
        "verificationPlan",
        "nextAgentId",
      ],
    },
  },
  {
    id: 3,
    name: "Media Intake Agent",
    purpose: "Handles uploads, captures, and turns media into Axis objects.",
    status: "Wired as static media intake contract.",
    futureWiring: "upload, Cloudflare/Mux, Supabase storage.",
    accent: "blue",
    mediaIntakeContract: {
      accepts: [
        "executionPlan from Axis LLM Orchestrator Agent",
        "uploaded file reference",
        "camera capture reference",
        "audio/video/image source metadata",
        "current session/player/project context",
      ],
      decides: [
        "whether the source is video, image, audio, document, or note",
        "which intake path should prepare the source",
        "what metadata must be attached before processing",
        "whether the source is ready for another Axis agent",
        "what safety or size limits need review before upload wiring",
      ],
      returns: [
        "axisSourceObject",
        "sourceType",
        "sourceMetadata",
        "storagePlan",
        "nextAgentId",
      ],
    },
  },
  {
    id: 4,
    name: "Voice Agent",
    purpose: "Listens in real time and turns speech into structured Axis data.",
    status: "Wired as static voice contract.",
    futureWiring: "mic, transcription, voice notes.",
    accent: "green",
    voiceContract: {
      accepts: [
        "executionPlan from Axis LLM Orchestrator Agent",
        "audio source object from Media Intake Agent",
        "live microphone intent",
        "speaker/session context",
        "current command or question",
      ],
      decides: [
        "whether speech is live input, a saved voice note, or media audio",
        "whether the voice source needs transcription, cleanup, or summary",
        "what structured note shape should be produced",
        "whether the result should return to Axis Router or another agent",
        "what confidence or review flag is needed before using the transcript",
      ],
      returns: [
        "voiceSourceObject",
        "transcriptPlan",
        "structuredVoiceNote",
        "reviewFlags",
        "nextAgentId",
      ],
    },
  },
  {
    id: 5,
    name: "Vision Agent",
    purpose: "Detects players, ball, objects, court areas, body positions, and more.",
    status: "Wired as static vision contract.",
    futureWiring: "vision/cv pipeline.",
    accent: "orange",
    visionContract: {
      accepts: [
        "executionPlan from Axis LLM Orchestrator Agent",
        "image or video source object from Media Intake Agent",
        "frame or clip reference",
        "current session/player/project context",
        "requested visual question or detection target",
      ],
      decides: [
        "whether the source needs image inspection or video frame analysis",
        "which visual observations should be suggested first",
        "whether player, ball, object, court, or body-position detection is relevant",
        "what confidence or review flag belongs on each suggested observation",
        "whether to hand off to Video Understanding Agent or return suggested observations",
      ],
      returns: [
        "suggestedVisualObservations",
        "detectionTargets",
        "frameReferences",
        "reviewFlags",
        "nextAgentId",
      ],
    },
  },
  {
    id: 6,
    name: "Video Understanding Agent",
    purpose: "Lets the user chat with video, find moments, patterns, and answers.",
    status: "Wired as static video understanding contract.",
    futureWiring: "video analysis, clips, summaries.",
    accent: "cyan",
    videoUnderstandingContract: {
      accepts: [
        "executionPlan from Axis LLM Orchestrator Agent",
        "video source object from Media Intake Agent",
        "suggestedVisualObservations from Vision Agent",
        "clip or timestamp reference",
        "user question about the video",
      ],
      decides: [
        "whether the user needs a moment, pattern, answer, clip, or summary",
        "which frames or time ranges should be inspected first",
        "what visual/audio/context signals should be combined",
        "whether the output should become a clip, note, report input, or next question",
        "whether to hand off to Session Memory Agent or Report Agent",
      ],
      returns: [
        "videoUnderstandingPlan",
        "momentCandidates",
        "patternCandidates",
        "answerDraft",
        "clipPlan",
        "nextAgentId",
      ],
    },
  },
  {
    id: 7,
    name: "Session Memory Agent",
    purpose: "Stores challenge, constraint, reality, result, and next challenge.",
    status: "Wired as static session memory contract.",
    futureWiring: "Supabase memory/session tables.",
    accent: "purple",
    sessionMemoryContract: {
      accepts: [
        "executionPlan from Axis LLM Orchestrator Agent",
        "source objects from Media Intake Agent",
        "voice, vision, or video understanding outputs",
        "current player/session/project context",
        "challenge, constraint, reality, result, and next challenge candidates",
      ],
      decides: [
        "which session facts are worth keeping",
        "which items are only temporary working context",
        "how challenge, constraint, reality, result, and next challenge should be separated",
        "whether the memory candidate needs user confirmation",
        "whether the next handoff is Report Agent or Follow-Up / Sales Agent",
      ],
      returns: [
        "sessionMemoryPlan",
        "memoryCandidates",
        "temporaryContext",
        "confirmationNeeded",
        "nextAgentId",
      ],
    },
  },
  {
    id: 8,
    name: "Report Agent",
    purpose: "Turns evidence into player, parent, coach, and team reports.",
    status: "Wired as static report contract.",
    futureWiring: "report generation, PDF/export, send/share.",
    accent: "gold",
    reportContract: {
      accepts: [
        "executionPlan from Axis LLM Orchestrator Agent",
        "sessionMemoryPlan from Session Memory Agent",
        "approved session facts and summaries",
        "clip, moment, or report input candidates",
        "intended audience: player, parent, coach, or team",
      ],
      decides: [
        "which report shape fits the audience",
        "which claims need support before appearing in the report",
        "which clips or moments should be referenced",
        "whether the report should stay draft-only",
        "whether to hand off to Follow-Up / Sales Agent after report approval",
      ],
      returns: [
        "reportDraftPlan",
        "audienceType",
        "supportedClaimList",
        "clipReferencePlan",
        "exportPlan",
        "nextAgentId",
      ],
    },
  },
  {
    id: 9,
    name: "Follow-Up / Sales Agent",
    purpose: "Turns proof into action: updates, bookings, next steps, parent follow-up.",
    status: "Wired as static follow-up contract.",
    futureWiring: "messages, automations, reminders, booking flows.",
    accent: "green",
    followUpContract: {
      accepts: [
        "executionPlan from Axis LLM Orchestrator Agent",
        "approved report plan from Report Agent",
        "sessionMemoryPlan from Session Memory Agent",
        "audience and consent context",
        "next challenge, booking, update, or reminder candidate",
      ],
      decides: [
        "which follow-up action is appropriate",
        "whether the action is a message, booking, reminder, update, or next challenge",
        "what approval is required before sending anything",
        "which audience should receive the follow-up",
        "whether the action should stay as a draft only",
      ],
      returns: [
        "followUpPlan",
        "audienceType",
        "draftMessage",
        "automationCandidate",
        "approvalRequired",
        "nextActionStatus",
      ],
    },
  },
];

export const axisBuildScreens: AxisBuildScreen[] = [
  {
    id: "home",
    title: "Home Screen",
    items: ["AXIS 9 identity", "New Session button", "Ask Axis button", "9 agent grid", "bottom navigation"],
  },
  {
    id: "sessions",
    title: "Sessions Screen",
    items: ["session list", "today / week / month filters", "processing and complete states"],
  },
  {
    id: "session-detail",
    title: "Session Detail Screen",
    items: ["video thumbnail", "summary", "clips", "notes", "stats", "challenge", "constraint", "result", "next challenge"],
  },
  {
    id: "ask-axis",
    title: "Ask Axis Screen",
    items: ["chat with video/session", "clip reference", "answer card", "next challenge", "mic input"],
  },
  {
    id: "player-profile",
    title: "Player Profile Screen",
    items: ["player image", "sessions", "challenges", "targets hit", "personal bests", "strengths", "opportunities"],
  },
  {
    id: "report",
    title: "Report Screen",
    items: ["player report", "grade", "summary", "strengths", "focus areas", "next challenge", "clips", "send to parent", "download PDF"],
  },
  {
    id: "how-axis-works",
    title: "How Axis Works Section",
    items: ["Capture", "Axis Agents", "Memory", "Proof", "Action"],
  },
];

export const axisSessionContract: AxisObjectContract = {
  name: "AxisSession",
  status: "Wired as local frontend object type.",
  owns: [
    "id",
    "title",
    "optional playerName",
    "sessionType",
    "status",
    "createdAt",
  ],
  doesNotOwn: [
    "media uploads",
    "analysis results",
    "agent execution",
    "proof or evidence",
    "memory persistence",
    "reports",
  ],
  futureWiring: [
    "session persistence",
    "media intake handoff",
    "session detail screen",
    "AxisOutput grouping",
  ],
};

export const axisPlayerContract: AxisObjectContract = {
  name: "AxisPlayer",
  status: "Wired as local frontend object type.",
  owns: [
    "id",
    "displayName",
    "optional jerseyNumber",
    "optional position",
    "status",
    "createdAt",
  ],
  doesNotOwn: [
    "long-term player memory",
    "verified performance truth",
    "stats",
    "media evidence",
    "reports",
    "cross-session history",
  ],
  futureWiring: [
    "player profile screen",
    "session association",
    "report audience context",
    "memory layer only after explicit unlock",
  ],
};

export const axisOutputContract: AxisObjectContract = {
  name: "AxisOutput",
  status: "Wired as universal output object type.",
  owns: [
    "id",
    "title",
    "output type",
    "status",
    "createdAt",
    "optional thumbnailUrl",
    "optional fileUrl",
    "optional summary",
    "optional sourceLabel",
  ],
  doesNotOwn: [
    "backend provider identity",
    "raw API credentials",
    "source truth",
    "verification verdicts",
    "memory records",
    "session persistence",
  ],
  futureWiring: [
    "/api/axis/run result envelope",
    "recent outputs surface",
    "output detail views",
    "artifact/export grouping",
  ],
};

export const axisMediaSourceContract: AxisObjectContract = {
  name: "AxisMediaSource",
  status: "Wired as local media intake draft.",
  owns: [
    "id",
    "fileName",
    "fileType",
    "mediaType",
    "sizeBytes",
    "status",
    "createdAt",
    "optional sessionId",
  ],
  doesNotOwn: [
    "uploaded file bytes",
    "storage URL",
    "Cloudflare/Mux asset",
    "analysis results",
    "evidence verdicts",
    "persistent source record",
  ],
  futureWiring: [
    "real upload transport",
    "storage asset creation",
    "Media Intake Agent handoff",
    "AxisOutput generation",
  ],
};

export const axisObjectContracts: AxisObjectContract[] = [
  axisSessionContract,
  axisPlayerContract,
  axisOutputContract,
  axisMediaSourceContract,
];

export const axisBuildOrder: AxisBuildOrderItem[] = [
  { id: 1, title: "Blank /axis shell" },
  { id: 2, title: "/axis/build-map page" },
  { id: 3, title: "Static Axis 9 agent cards" },
  { id: 4, title: "Static mobile screen references" },
  { id: 5, title: "New Session button" },
  { id: 6, title: "Ask Axis input" },
  {
    id: 7,
    title: "Session object type",
    items: ["AxisSession type exists", "local draft status only", "no persistence yet"],
  },
  {
    id: 8,
    title: "Player object type",
    items: ["AxisPlayer type exists", "profile identity only", "no player memory yet"],
  },
  {
    id: 9,
    title: "AxisOutput object type",
    items: ["AxisOutput type exists", "all result categories share one shape", "no run API wiring yet"],
  },
  {
    id: 10,
    title: "Media intake upload",
    items: ["local file picker exists", "metadata draft only", "no backend upload yet"],
  },
  {
    id: 11,
    title: "Session detail page",
    items: ["local detail surface opens", "shows session facts and drafts", "no route or persistence yet"],
  },
  {
    id: 12,
    title: "Ask Axis chat page",
    items: ["local chat surface exists", "messages stay in frontend state", "no agent response yet"],
  },
  {
    id: 13,
    title: "Player profile page",
    items: ["local profile preview opens", "uses current session player only", "no player memory yet"],
  },
  {
    id: 14,
    title: "Report page",
    items: ["local report draft opens", "shows current session inputs", "no generation, export, or send yet"],
  },
  {
    id: 15,
    title: "Memory persistence",
    items: ["browser localStorage restore exists", "draft session state only", "no Supabase or player memory yet"],
  },
  {
    id: 16,
    title: "Report export/send",
    items: ["local export/send draft actions exist", "no PDF generated", "nothing is sent yet"],
  },
  {
    id: 17,
    title: "Follow-up automation",
    items: ["local follow-up draft action exists", "no message sent", "no automation scheduled yet"],
  },
  {
    id: 18,
    title: "Backend read: Recent Axis Outputs",
    items: [
      "reads existing artifact and export histories",
      "maps backend records into AxisOutput",
      "read-only integration with static fallback",
      "no /api/axis/run wiring yet",
    ],
  },
  {
    id: 19,
    title: "Output Detail preview",
    items: [
      "recent output cards open a local detail preview",
      "shows mapped AxisOutput fields only",
      "open link appears when fileUrl exists",
      "read-only selection state with no persistence",
    ],
  },
  {
    id: 20,
    title: "Static command composer",
    items: [
      "composer creates local pending AxisOutput drafts",
      "pending outputs appear in Recent Outputs",
      "no /api/axis/run request yet",
      "no backend writes or session persistence",
    ],
  },
  {
    id: 21,
    title: "Local command mode selection",
    items: [
      "composer can draft text, report, video, file, or automation outputs",
      "selected mode sets the local AxisOutput type",
      "mode choice stays frontend-only",
      "no /api/axis/run request yet",
    ],
  },
  {
    id: 22,
    title: "Local active run progress",
    items: [
      "latest pending output appears in an active run panel",
      "shows local queued/routing/drafting stages",
      "progress is presentation-only",
      "no /api/axis/run request or backend job yet",
    ],
  },
  {
    id: 23,
    title: "Local output lifecycle",
    items: [
      "pending local outputs transition from processing to ready",
      "ready state updates the local output summary",
      "lifecycle is timer-based frontend state only",
      "no /api/axis/run request or backend job yet",
    ],
  },
  {
    id: 24,
    title: "Local failed-state simulation",
    items: [
      "composer can simulate a failed local output",
      "failed outputs update after the local lifecycle delay",
      "active run panel shows a failed preview stage",
      "no /api/axis/run request or backend error wiring yet",
    ],
  },
  {
    id: 25,
    title: "Local retry for failed outputs",
    items: [
      "failed local outputs expose a retry action in detail preview",
      "retry returns the output to processing",
      "same frontend lifecycle moves retry to ready",
      "no backend retry, job, or route wiring yet",
    ],
  },
  {
    id: 26,
    title: "Clear local preview outputs",
    items: [
      "local preview outputs can be cleared from Recent Outputs",
      "backend-sourced outputs remain untouched",
      "failure bookkeeping clears with local previews",
      "no delete route, persistence, or backend mutation",
    ],
  },
  {
    id: 27,
    title: "Recent Outputs count summary",
    items: [
      "Recent Outputs shows local preview count separately from saved output count",
      "fallback records are labeled as examples, not saved backend data",
      "summary updates from frontend state only",
      "no backend route, write, or persistence change",
    ],
  },
  {
    id: 28,
    title: "Local run request preview",
    items: [
      "composer submissions create a typed local /api/axis/run request preview",
      "preview captures input, selected output type, session attachment, and media attachment",
      "active run card displays the preview contract quietly",
      "no /api/axis/run call, backend write, or job execution yet",
    ],
  },
  {
    id: 29,
    title: "Local run history preview",
    items: [
      "last few local run request previews stay visible in the active run card",
      "history shows command text and selected output type",
      "history clears with local preview outputs",
      "no persistence, route call, backend job, or analytics tracking yet",
    ],
  },
  {
    id: 30,
    title: "Local run payload validation",
    items: [
      "composer validates local run previews before creating outputs",
      "empty, too-long, unsupported, and media-required previews show quiet inline errors",
      "invalid previews do not enter Recent Outputs or run history",
      "no /api/axis/run call, backend validation route, or persistence yet",
    ],
  },
  {
    id: 31,
    title: "Local media attachment badge",
    items: [
      "composer shows the current local media attachment when one exists",
      "badge displays media type, file name, size, and ready-for-preview state",
      "remove clears local attachment state so video/file validation requires media again",
      "no upload system, backend route, storage delete, or persistence yet",
    ],
  },
  {
    id: 32,
    title: "Local attachment-to-run preview linkage",
    items: [
      "local run previews snapshot the attachment used at creation time",
      "local AxisOutput drafts retain the same attachment snapshot",
      "active run and output detail surfaces show which attachment was used",
      "no upload, backend call, storage write, or persistence yet",
    ],
  },
  {
    id: 33,
    title: "Local run readiness summary",
    items: [
      "composer shows whether the selected mode is ready for a local preview",
      "video and file modes explain when media must be attached",
      "readiness updates from command text, selected mode, and local attachment state",
      "no validation rule, backend route, /api/axis/run call, or persistence change",
    ],
  },
  {
    id: 34,
    title: "Local active run completion summary",
    items: [
      "active run card shows the local completion or failure summary after processing",
      "completion copy comes from the existing local AxisOutput summary",
      "processing state remains quiet until the local preview finishes",
      "no backend route, /api/axis/run call, persistence, or type change",
    ],
  },
  {
    id: 35,
    title: "Local run source trace",
    items: [
      "output detail preview shows the local command that created a preview output",
      "trace resolves through the existing local run preview expectedOutputId",
      "shows selected mode, target route, and local preview time",
      "no backend fetch, write, route change, persistence, or AxisOutput type change",
    ],
  },
  {
    id: 36,
    title: "Local output duplicate guard",
    items: [
      "rapid repeated submits no longer create duplicate processing previews",
      "duplicate check compares normalized command text and selected output type",
      "finished ready or failed outputs do not permanently block a new preview",
      "no backend route, /api/axis/run call, persistence, or validation API change",
    ],
  },
  {
    id: 37,
    title: "Local clear selected-output safety",
    items: [
      "clearing local previews closes the detail preview when it belongs to a cleared local output",
      "saved or fallback output detail state remains independent of local preview clearing",
      "clear action still removes local previews only",
      "no backend delete, route change, persistence, or output type change",
    ],
  },
  {
    id: 38,
    title: "Local run retry trace update",
    items: [
      "retrying a failed local output creates a fresh local run preview entry",
      "retry preview stays tied to the same local AxisOutput through expectedOutputId",
      "active run and output detail surfaces can show the latest retry trace",
      "no backend retry, /api/axis/run call, route change, persistence, or type change",
    ],
  },
  {
    id: 39,
    title: "Local output empty-state reset polish",
    items: [
      "Recent Outputs header returns to saved or example history after local previews are cleared",
      "local preview label appears only while local previews exist",
      "count summary separates local previews from saved or example outputs cleanly",
      "no backend fetch change, route change, persistence, or output type change",
    ],
  },
  {
    id: 40,
    title: "Local Axis shell checkpoint commit",
    items: [
      "local output shell steps 18 through 39 were committed as one checkpoint",
      "frontend shell remains local/read-only except recent output reads",
      "backend routes and /api/axis/run wiring remain untouched",
      "checkpoint commit 32dbce0 was pushed",
    ],
  },
  {
    id: 41,
    title: "Local Axis run payload envelope",
    items: [
      "local run previews can be converted into a typed future /api/axis/run payload",
      "active run card shows when the local payload envelope is ready",
      "payload helper is pure frontend contract preparation only",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 42,
    title: "Local run payload detail preview",
    items: [
      "output detail preview shows the future run payload summary for local previews",
      "payload display uses the same typed envelope as the active run card",
      "route, mode, session, and media fields are visible without provider details",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 43,
    title: "Local run result envelope",
    items: [
      "local preview outputs can be wrapped in a typed future run result envelope",
      "output detail preview shows the result envelope status without backend execution",
      "result envelope points back to the same local AxisOutput and payload contract",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 44,
    title: "Local run execution lock",
    items: [
      "frontend exposes a shared execution state for future /api/axis/run wiring",
      "active run and output detail surfaces show that execution is currently locked",
      "the prepared payload/result contracts remain visible without starting a run",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 45,
    title: "Local run locked handoff action",
    items: [
      "output detail preview shows a disabled Run locked handoff action for local previews",
      "the action confirms that future execution is prepared but intentionally unavailable",
      "retry and open-output actions still behave as local/read-only previews",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 46,
    title: "Local composer execution boundary",
    items: [
      "composer footer uses the shared execution state instead of one-off copy",
      "the command surface tells users that run wiring is prepared but locked",
      "active run, output detail, and composer now share one local execution boundary",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 47,
    title: "Local run contract preview",
    items: [
      "payload, result envelope, and execution lock are grouped into one typed local contract preview",
      "active run and output detail surfaces use the same contract helper",
      "local previews can show whether the run contract matches the expected output",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 48,
    title: "Local run contract type layer",
    items: [
      "future run payload, result envelope, execution state, and contract preview types live in the shared Axis type layer",
      "client helpers now import the shared contract types instead of declaring them locally",
      "the frontend contract is easier to reuse when /api/axis/run wiring begins",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 49,
    title: "Local run contract validation",
    items: [
      "frontend can validate that a local run contract has a payload, matching route, and matched output link",
      "active run and output detail surfaces show the local contract check result",
      "validation is a pure frontend guard for future /api/axis/run wiring",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 50,
    title: "Local output contract status",
    items: [
      "local preview output cards show a quiet contract status before opening detail",
      "status comes from the same local contract validation helper",
      "backend, saved, and fallback outputs do not get fake run contract labels",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 51,
    title: "Local contract readiness summary",
    items: [
      "Recent Outputs summary counts local preview contracts that are ready or need review",
      "summary is derived from the same local contract validation helper as cards and detail",
      "saved, backend, and fallback outputs remain separate from local contract health",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 52,
    title: "Local run target route constant",
    items: [
      "future /api/axis/run route target is centralized as a frontend contract constant",
      "local preview creation and retry use the shared route constant",
      "execution-state helper uses the same route target",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 53,
    title: "Local composer target visibility",
    items: [
      "composer footer displays the shared future run target route from execution state",
      "target copy comes from the same contract constant used by preview creation and retry",
      "the command surface remains locked and display-only",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 54,
    title: "Local run wiring checklist",
    items: [
      "active run card shows which frontend run-contract pieces are ready",
      "checklist marks backend execution as locked until run wiring is explicitly enabled",
      "checklist is derived from local client contract helpers only",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 55,
    title: "Local output detail wiring checklist",
    items: [
      "output detail preview shows the same local run wiring checklist as the active run card",
      "frontend contract readiness and locked backend execution remain visible while inspecting an output",
      "checklist appears only for local preview outputs with a run contract",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 56,
    title: "Local run submit guard",
    items: [
      "frontend can decide whether a local run contract is submit-ready, needs review, or locked",
      "active run card shows the submit decision without enabling execution",
      "output detail handoff button uses the shared submit guard label and message",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 57,
    title: "Local output submit status",
    items: [
      "local preview output cards show both contract readiness and submit guard status",
      "cards can say contract ready while run execution remains locked",
      "status comes from the same submit guard used by active run and detail",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 58,
    title: "Local submit readiness summary",
    items: [
      "Recent Outputs summary counts local previews that are submit-ready or run-locked",
      "summary is derived from the same submit guard used by cards, active run, and detail",
      "locked execution remains visible at the surface level before backend wiring",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 59,
    title: "Local run sender lock message",
    items: [
      "dormant sendAxisRun helper now uses the shared execution lock message",
      "accidental frontend calls fail with the same boundary shown in the UI",
      "run target remains prepared but intentionally disabled",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 60,
    title: "Local run contract checkpoint",
    items: [
      "local payload, result envelope, validation, submit guard, and wiring checklist are now represented",
      "the shell can show prepared-but-locked run state before backend wiring begins",
      "next real build decision should choose whether to wire /api/axis/run or commit this frontend contract checkpoint first",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 61,
    title: "Local run route compatibility guard",
    items: [
      "frontend contract now records that current /api/axis/run is legacy AxisUnderstanding, not unified AxisOutput transport",
      "active run card and submit guard show Adapter needed before execution can be enabled",
      "wiring checklist includes route adapter as a required missing piece",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 62,
    title: "Local run adapter contract",
    items: [
      "frontend defines the adapter contract needed between AxisRunPayload and AxisOutput",
      "adapter contract records expected accepts and returns shape for future route wiring",
      "active run card shows adapter status as needed",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 63,
    title: "Local output detail compatibility guard",
    items: [
      "output detail preview shows the same route compatibility guard as the active run card",
      "inspected outputs state that the current /api/axis/run route needs an AxisOutput adapter",
      "submit guard and wiring checklist remain locked until adapter work is explicit",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 64,
    title: "/api/axis/run AxisOutput adapter contract",
    items: [
      "adapter contract previews the legacy /api/axis/run POST payload and expected response shape",
      "output detail shows route, method, compatibility, dry-run-only state, submit lock, missing requirements, and AxisOutput mapping",
      "active run card shows adapter contract readiness without unlocking submit",
      "adapter contract only / no route calls / no side effects",
    ],
  },
  {
    id: 65,
    title: "Local adapter dry-run simulation",
    items: [
      "output detail previews what the adapter would send, receive, and create as an AxisOutput",
      "dry-run simulation explicitly records that no route was called",
      "dry-run output remains a local preview object only",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 66,
    title: "Local dry-run route guard",
    items: [
      "frontend distinguishes local dry-run simulation from an actual route dry run",
      "active run card and output detail show dry-run routing as locked",
      "guard is local contract state only and does not call /api/axis/run",
      "no backend call, route change, persistence, or run execution yet",
    ],
  },
  {
    id: 68,
    title: "/api/axis/run dry-run handshake",
    items: [
      "local preview outputs can test /api/axis/run with dryRun true only",
      "route returns a typed execution plan preview with no write, no job, no upload, and no model call",
      "dry-run responses stay in the detail preview and never become Recent Outputs",
      "route dry-run only / no side effects / submit locked",
    ],
  },
  {
    id: 69,
    title: "Dry-run adapter status preview",
    items: [
      "successful route dry-runs map into a local adapter handshake status",
      "detail preview shows accepted route, next agent, output type, and submit-locked state",
      "no-write, no-job, no-model-call, and no-upload guarantees remain visible after the handshake",
      "status preview only / no output creation / no real submit unlock",
    ],
  },
  {
    id: 70,
    title: "Active run dry-run handshake status",
    items: [
      "route dry-run results are lifted into the active run status card for the matching local output",
      "active run shows adapter handshake, next agent, no-side-effect guarantees, and submit-locked state",
      "dry-run result remains local UI state keyed by output id",
      "no output creation / no persistence / no real submit unlock",
    ],
  },
  {
    id: 71,
    title: "Local route dry-run history",
    items: [
      "recent route dry-run results are tracked in local UI state",
      "active run card shows the last few route dry-run checks with ready or review status",
      "history clears with local preview outputs and never becomes Recent Outputs",
      "local history only / no persistence / no real submit unlock",
    ],
  },
  {
    id: 72,
    title: "Dry-run payload inspector",
    items: [
      "output detail can reveal the dry-run request and response payloads after a route test",
      "payload inspector is hidden behind a local toggle and remains read-only",
      "inspector does not add dry-run data to Recent Outputs or active run history",
      "detail-only inspector / no persistence / no real submit unlock",
    ],
  },
  {
    id: 73,
    title: "Real submit readiness summary",
    items: [
      "active run and output detail summarize what is complete locally before real submit",
      "summary separates completed contract pieces from remaining execution requirements",
      "remaining requirements include the real AxisOutput adapter, execution unlock, submit policy, and side-effect gates",
      "readiness summary only / no route execution / no real submit unlock",
    ],
  },
  {
    id: 74,
    title: "Route dry-run checkpoint commit",
    items: [
      "steps 68 through 73 are grouped as the route dry-run handshake checkpoint",
      "checkpoint includes dry-run route branch, adapter status, history, payload inspector, and submit readiness summary",
      "real submit remains locked after the checkpoint",
      "checkpoint only / no jobs / no writes / no uploads / no model calls",
    ],
  },
];
