export const CALIBRATION_LANGUAGE = {
  CHECKED_IN: "CHECKED IN",
  MOVE_AROUND: "MOVE AROUND",
  PLAYER_FOUND: "PLAYER FOUND",
  STEP_INTO_FRAME: "STEP INTO FRAME",
  START: "START",
  TRACKING_READY: "TRACKING READY",
  TRAINING_ACTIVE: "TRAINING ACTIVE",
} as const

export type CalibrationState =
  | typeof CALIBRATION_LANGUAGE.CHECKED_IN
  | typeof CALIBRATION_LANGUAGE.STEP_INTO_FRAME
  | typeof CALIBRATION_LANGUAGE.PLAYER_FOUND
  | typeof CALIBRATION_LANGUAGE.MOVE_AROUND
  | typeof CALIBRATION_LANGUAGE.TRACKING_READY
  | typeof CALIBRATION_LANGUAGE.TRAINING_ACTIVE
