export const CALIBRATION_LANGUAGE = {
  ACTIVE: "ACTIVE",
  COMPLETE: "COMPLETE",
  HOLD_STILL: "HOLD STILL",
  LOST: "LOST",
  MOVE: "MOVE",
  READY: "READY",
  START: "START",
  TRACKING: "TRACKING",
  UPDATED: "UPDATED",
} as const

export type CalibrationState =
  | typeof CALIBRATION_LANGUAGE.READY
  | typeof CALIBRATION_LANGUAGE.HOLD_STILL
  | typeof CALIBRATION_LANGUAGE.MOVE
  | typeof CALIBRATION_LANGUAGE.TRACKING
  | typeof CALIBRATION_LANGUAGE.LOST
